// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prefer a direct (non-pooled) connection for CLI commands like `db push`
    // and `migrate`, since pgbouncer's transaction mode can't grant the
    // advisory lock the schema engine needs. The app's runtime Prisma client
    // (src/lib/prisma.ts) always uses DATABASE_URL directly and never reads
    // this file, so this only affects CLI operations.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
